name: AWS EC2 Manage Instance

on:
  workflow_dispatch:
    inputs:
      action:
        type: choice
        description: 'Start or Stop the EC2 instance'
        options:
        - start
        - stop
        required: true

env:
  EC2_INSTANCE_ID: i-0df2cb9b9508c4401

jobs:
  manage-instance:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: 'us-east-1'

    - name: Start EC2 Instance
      if: ${{ github.event.inputs.action == 'start' }}
      run: |
        aws ec2 start-instances --instance-ids ${{ env.EC2_INSTANCE_ID }}
        # Esperar que la instancia esté corriendo (opcional)
        aws ec2 wait instance-running --instance-ids ${{ env.EC2_INSTANCE_ID }}
        # Ejecutar script via SSH
        echo "VM_PUBLIC_IP=$(aws ec2 describe-instances --instance-ids $INSTANCE_ID --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)" >> $GITHUB_ENV
        sleep 10
        echo $VM_PUBLIC_IP

    - name: executing remote ssh commands
      if: ${{ github.event.inputs.action == 'start' }}
      uses: appleboy/ssh-action@v1.0.1
      with:
        host: ${{ env.VM_PUBLIC_IP }}
        username: ubuntu
        key: ${{ secrets.KEY }}
        port: 22
        script: |
          cd /home/ubuntu/proyectos/se-nutricion-backend/backend
          git pull
          ./start_backend.sh

    - name: Stop EC2 Instance
      if: ${{ github.event.inputs.action == 'stop' }}
      run: |
        aws ec2 stop-instances --instance-ids ${{ env.EC2_INSTANCE_ID }}
